[package]
name = "yofi"
version = "0.1.3"
authors = ["Kitsu <mail@kitsu.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
wayland-protocols = { version = "0.28.2", default-features = false, features = ["unstable_protocols", "client"] }
sctk = { version = "0.12.0", package = "smithay-client-toolkit", default-features = false, features = ["calloop"] }
raqote = { git = "https://github.com/l4l/raqote.git", rev = "27cfc13", default-features = false, features = ["text"] }
font-kit = "0.10"
xdg = "2.2.0"
fep = { version = "1.1.1", package = "freedesktop_entry_parser" }
shlex = "0.1.1"
nix = "0.19.1"
log = "0.4.11"
fern = "0.6.0"
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
serde = { version = "1.0.117", features = ["derive"] }
toml = "0.5.7"
structopt = "0.3.21"
either = "1.6.1"
png = { version = "0.16.7", default-features = false }
resvg = { version = "0.12.0", default-features = false }
usvg = { version = "0.12.0", default-features = false }
once_cell = "1.5.2"
fzyr = { git = "https://github.com/l4l/fzyr.git", rev = "d5c83e3", default-features = false }
oneshot = { version = "0.1.2", default-features = false, features = ["std"] }
bit-vec = "0.6.3"
itertools = "0.9.0"
euclid = "0.22.1"
nom = { version = "6.0.1", default-features = false, features = ["std", "regexp"] }
regex = "1.4.2"
libc = "0.2.81"

[profile.release]
lto = true

[dev-dependencies]
test-case = "1.0.0"
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
